# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up Docker Compose
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
        
    - name: Run Docker Compose
      run: docker-compose up -d
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Unit tests
      run: mvn -B verify

    - name: Coverage per Test Execution
      run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
          ${{ github.workspace }}/target
          ${{ github.workspace }}/reports
      
    - name: Sonar Code Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gabi-teste_vollmed

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        reporter: java-junit
        java-version: 17
